services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    restart: on-failure
    environment:





        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092'
        KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092,EXTERNAL://localhost:29092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
        KAFKA_CREATE_TOPICS: 'client:1:1'
        KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
    depends_on:
      - zookeeper

  discovery-service:
    build: ./discovery
    container_name: discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
    depends_on:
      - kafka
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
        discovery-service:
            condition: service_healthy

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
        interval: 10s
  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8090:8090"
    expose:
      - "8090"
    environment:
      - TOPIC =client
      - ENVIRONMENT= local
      - INTERNAL_KAFKA_ADDR= 'kafka:9092'
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
      - KAFKA_URL=kafka:9092
      - EXTERNAL_KAFKA_ADDR= 'kafka:29092'

    depends_on:
       config-service:
            condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8091:8091"
    expose:
      - "8091"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
        interval: 10s
  sale-service:
    build: ./sale-service
    container_name: sale-service
    ports:
      - "8092:8092"
    expose:
      - "8092"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
          condition: service_healthy
        product-service:
          condition: service_healthy
        client-service:
          condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
        interval: 10s
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
          condition: service_healthy
        product-service:
          condition: service_healthy
        client-service:
          condition: service_healthy
        sale-service:
          condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 10s
  notifiction-server:
    build: ./notification-service
    container_name: notifiction-server
    ports:
      - "8093:8093"
    expose:
      - "8093"
    environment:
      - TOPIC = client
      - ENVIRONMENT= local
      - INTERNAL_KAFKA_ADDR= 'kafka:9092'
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
      - KAFKA_URL=kafka:9092
      - EXTERNAL_KAFKA_ADDR= 'kafka:29092'

    depends_on:
      config-service:
            condition: service_healthy

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8093/actuator/health"]
        interval: 10s
  front-end-angular:
    build: ./front-end-angular
    container_name: front-end-angular
    ports:
      - "80:80"
    expose:
      - "80"



