services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
        discovery-service:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
        interval: 10s
  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8090:8090"
    expose:
      - "8090"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
       config-service:
            condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 10s
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8091:8091"
    expose:
      - "8091"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/health"]
        interval: 10s
  sale-service:
    build: ./sale-service
    container_name: sale-service
    ports:
      - "8092:8092"
    expose:
      - "8092"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
          condition: service_healthy
        product-service:
          condition: service_healthy
        client-service:
          condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
        interval: 10s
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_URL=http://config-service:9999
    depends_on:
        config-service:
          condition: service_healthy
        product-service:
          condition: service_healthy
        client-service:
          condition: service_healthy
        sale-service:
          condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
        interval: 10s