spring:
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8090
          predicates:
            - Path=/clients/**
        - id: product-service
          uri: http://localhost:8091
          predicates:
            - Path=/products/**